# Generated by Django 4.2.6 on 2024-01-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='img2',
            field=models.ImageField(default=1, upload_to='Banner/img'),
            preserve_default=False,
        ),
    ]
