# Generated by Django 4.2.6 on 2024-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_banner_img2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oldprice', models.IntegerField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='Devices/img')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
