# Generated by Django 4.2.6 on 2024-01-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
